sudo: required

language: node

services:
  - docker

branches:
  only:
  - demo

jobs:
  include:
    - stage: Flowz-Dashboard-Fronted-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t flowz_dashboard_fronted_flowz:demo .
      - docker images
      - docker tag flowz_dashboard_fronted_flowz:demo $DOCKER_USERNAME/flowz_dashboard_fronted_flowz:demo
      - docker push $DOCKER_USERNAME/flowz_dashboard_fronted_flowz:demo
    - stage: Upgrade Rancher Service
      script:
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh
